pipeline{
    agent any
   tools {
        maven 'M3'
        jdk 'JAVA_HOME'
    }
    stages{
          stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
            }
        }
       
         stage ('Build') {
            steps {
                sh 'mvn -f mjdDemoPipeline/pom.xml clean package'
            }
           
        }
        
        stage('Create Dockerfile'){
            steps{   
                sh '''
                   
                    cp /var/lib/jenkins/workspace/mjd_pipeline/mjdDemoPipeline/target/mjdDemoPipeline-0.0.1-SNAPSHOT.war .
                    touch Dockerfile
                   
                    From tomcat
                    ADD mjdDemoPipeline-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps
                    CMD "catalina.sh" "run"
                    EXPOSE 8080
                    
                   
                '''
            }
        } 
        
        stage('Build Image'){
            steps{
               sh 'sudo docker build -t mydeploy2:$BUILD_NUMBER .'
               sh 'sudo docker run -itd -P mydeploy2:$BUILD_NUMBER'
            }
        }
       
 
      
    }
}
