pipeline{
    agent any
   tools {
        maven 'M3'
        jdk 'JAVA_HOME'
    }
    stages{
          stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
            }
        }
       
         stage ('Build') {
            steps {
                sh 'mvn -f mjdDemoPipeline/pom.xml clean package'
            }
           
        }
       
        
        stage('Build Image'){
            steps{
               sh 'sudo docker build -t mydeploy2:$BUILD_NUMBER .'
               sh 'sudo docker run -itd -P mydeploy2:$BUILD_NUMBER'
            }
        }
       
 
      
    }
}
